steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mitrixogymcrm:${_TAG}', '--build-arg', 'VITE_BUILD_COMMIT=${_TAG}', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mitrixogymcrm:${_TAG}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mitrixogymcrm'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mitrixogymcrm:${_TAG}'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/mitrixogymcrm:${_TAG}'

substitutions:
  _TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
