import React, { useState, useEffect, useRef, useMemo } from 'react';
import { useAppContext } from '../context';
import { useTasks } from '../hooks/useTasks';
import { useAuth } from '../contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Bell, AlertTriangle, Gift, CheckSquare, Clock, X, Check, ShoppingCart, Volume2 } from 'lucide-react';
import { differenceInDays, isSameDay, isSameMonth, parseISO, isToday, isBefore, isAfter, startOfDay } from 'date-fns';
import { db } from '../firebase';
import { arrayUnion, collection, doc, limit, onSnapshot, orderBy, query, updateDoc, where } from 'firebase/firestore';

export type NotificationType = 'lead_stale' | 'member_expiring' | 'birthday' | 'task_due' | 'booking_request' | 'class_booking_created' | 'class_waitlist_joined' | 'system';

export interface AppNotification {
  id: string;
  type: NotificationType;
  title: string;
  description: string;
  date: Date;
  recordName: string;
  recordId: string;
  source?: 'generated' | 'system';
  readBy?: string[];
  data?: Record<string, any>;
}

export function NotificationCenter() {
  const { clients, setSearchQuery, setActiveTab, setActiveClientId } = useAppContext();
  const { currentUser, updateUser } = useAuth();
  const { tasks } = useTasks();
  const [isOpen, setIsOpen] = useState(false);
  const [notifications, setNotifications] = useState<AppNotification[]>([]);
  const [dismissedIds, setDismissedIds] = useState<Set<string>>(new Set());
  const [pendingBookings, setPendingBookings] = useState<any[]>([]);
  const [systemNotifications, setSystemNotifications] = useState<AppNotification[]>([]);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const hasSeenInitialSystemSnapshot = useRef(false);
  const soundEnabledRef = useRef(true);

  const playAlertSound = () => {
    if (!soundEnabledRef.current) return;
    try {
      const AudioContextClass = window.AudioContext || (window as any).webkitAudioContext;
      if (!AudioContextClass) return;
      const ctx = new AudioContextClass();
      const gain = ctx.createGain();
      gain.gain.setValueAtTime(0.0001, ctx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.18, ctx.currentTime + 0.02);
      gain.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + 0.55);
      gain.connect(ctx.destination);

      [880, 1174].forEach((freq, index) => {
        const osc = ctx.createOscillator();
        osc.type = 'sine';
        osc.frequency.setValueAtTime(freq, ctx.currentTime + index * 0.12);
        osc.connect(gain);
        osc.start(ctx.currentTime + index * 0.12);
        osc.stop(ctx.currentTime + index * 0.12 + 0.18);
      });
      setTimeout(() => ctx.close().catch(() => {}), 900);
    } catch (err) {
      console.warn('[Notifications] Could not play alert sound:', err);
    }
  };

  // Subscribe to pending booking requests
  useEffect(() => {
    const q = query(collection(db, 'bookingRequests'), where('status', '==', 'Pending'));
    const unsub = onSnapshot(q, (snapshot) => {
      const list = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      }));
      setPendingBookings(list);
    }, (err) => {
      console.error("Error loading pending bookings for notifications:", err);
    });
    return () => unsub();
  }, []);

  // Subscribe to durable staff system notifications generated by server/cloud functions.
  useEffect(() => {
    if (!currentUser?.id || currentUser.role === 'client') return;
    const q = query(
      collection(db, 'systemNotifications'),
      orderBy('createdAt', 'desc'),
      limit(75)
    );

    const unsub = onSnapshot(q, (snapshot) => {
      const addedBookingAlerts = snapshot.docChanges().filter(change => {
        const data = change.doc.data();
        return change.type === 'added' &&
          (data.type === 'class_booking_created' || data.type === 'class_waitlist_joined');
      });

      const rows = snapshot.docs.map(d => {
        const data = d.data();
        return {
          id: d.id,
          type: data.type || 'system',
          title: data.title || 'System notification',
          description: data.body || data.description || '',
          date: data.createdAt ? parseISO(data.createdAt) : new Date(),
          recordName: data.data?.memberName || data.data?.className || 'System',
          recordId: data.data?.clientId || data.data?.classId || d.id,
          source: 'system' as const,
          readBy: Array.isArray(data.readBy) ? data.readBy : [],
          data: data.data || {}
        } as AppNotification;
      });
      setSystemNotifications(rows);

      if (hasSeenInitialSystemSnapshot.current && addedBookingAlerts.length > 0) {
        playAlertSound();
      }
      hasSeenInitialSystemSnapshot.current = true;
    }, (err) => {
      console.error('[Notifications] Error loading system notifications:', err);
    });

    return () => unsub();
  }, [currentUser?.id, currentUser?.role]);

  // Load dismissed notifications from database and localStorage on mount
  useEffect(() => {
    if (currentUser?.id) {
      const dbDismissed = currentUser.dismissedNotifications || [];
      const stored = localStorage.getItem(`crm_notifications_dismissed_${currentUser.id}`);
      const mergedSet = new Set<string>(dbDismissed);
      
      if (stored) {
        try {
          const parsed = JSON.parse(stored);
          if (Array.isArray(parsed)) {
            parsed.forEach(id => mergedSet.add(id));
          }
        } catch (e) {
          console.error("Failed to parse dismissed notifications from localStorage", e);
        }
      }
      setDismissedIds(mergedSet);
    }
  }, [currentUser?.id, currentUser?.dismissedNotifications]);

  // Save dismissed notifications to database and localStorage when changed
  const dismissNotification = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!currentUser?.id) return;

    const systemNotification = systemNotifications.find(n => n.id === id);
    if (systemNotification) {
      updateDoc(doc(db, 'systemNotifications', id), {
        readBy: arrayUnion(currentUser.id),
        updatedAt: new Date().toISOString()
      }).catch(err => {
        console.error("Failed to mark system notification read", err);
      });
      return;
    }
    
    setDismissedIds(prev => {
      const next = new Set(prev);
      next.add(id);
      const arr = Array.from(next);
      localStorage.setItem(`crm_notifications_dismissed_${currentUser.id}`, JSON.stringify(arr));
      // Save to database
      updateUser(currentUser.id, { dismissedNotifications: arr }).catch(err => {
        console.error("Failed to save dismissed notification to DB", err);
      });
      return next;
    });
  };

  const dismissAll = () => {
    if (!currentUser?.id) return;
    const allIds = notifications.filter(n => n.source !== 'system').map(n => n.id);
    systemNotifications
      .filter(n => !(n.readBy || []).includes(currentUser.id))
      .forEach(n => {
        updateDoc(doc(db, 'systemNotifications', n.id), {
          readBy: arrayUnion(currentUser.id),
          updatedAt: new Date().toISOString()
        }).catch(err => console.error("Failed to mark system notification read", err));
      });
    setDismissedIds(prev => {
      const next = new Set(prev);
      allIds.forEach(id => next.add(id));
      const arr = Array.from(next);
      localStorage.setItem(`crm_notifications_dismissed_${currentUser.id}`, JSON.stringify(arr));
      // Save to database
      updateUser(currentUser.id, { dismissedNotifications: arr }).catch(err => {
        console.error("Failed to save dismissed notifications to DB", err);
      });
      return next;
    });
    setIsOpen(false);
  };

  // Click outside to close
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Generate notifications
  useEffect(() => {
    const today = startOfDay(new Date());
    const generated: AppNotification[] = [];

    // 1. Leads not contacted in 7+ days
    // 2. Members expiring in 3 days
    // 3. Birthdays today
    clients.forEach(client => {
      // Birthdays
      if (client.dateOfBirth) {
        const dob = parseISO(client.dateOfBirth);
        if (dob.getMonth() === today.getMonth() && dob.getDate() === today.getDate()) {
          generated.push({
            id: `bday_${client.id}_${today.getFullYear()}`,
            type: 'birthday',
            title: 'Birthday Today!',
            description: `${client.name} is celebrating their birthday today.`,
            date: today,
            recordName: client.name,
            recordId: client.id
          });
        }
      }

      if (client.status === 'Lead') {
        // Stale leads
        if (client.lastContactDate) {
          const lastContact = parseISO(client.lastContactDate);
          const daysPassed = differenceInDays(today, startOfDay(lastContact));
          if (daysPassed >= 7) {
            generated.push({
              id: `lead_stale_${client.id}_${lastContact.toISOString()}`,
              type: 'lead_stale',
              title: 'Stale Lead',
              description: `${client.name} hasn't been contacted in ${daysPassed} days.`,
              date: lastContact,
              recordName: client.name,
              recordId: client.id
            });
          }
        }
      } else if (client.status !== 'Hold') {
        // Expiring members
        if (client.membershipExpiry) {
          const expiryDate = parseISO(client.membershipExpiry);
          const daysToExpiry = differenceInDays(startOfDay(expiryDate), today);
          
          if (daysToExpiry >= 0 && daysToExpiry <= 3) {
            generated.push({
              id: `expiring_${client.id}_${expiryDate.toISOString()}`,
              type: 'member_expiring',
              title: 'Membership Expiring',
              description: `${client.name}'s membership expires in ${daysToExpiry === 0 ? 'today' : `${daysToExpiry} days`}.`,
              date: expiryDate,
              recordName: client.name,
              recordId: client.id
            });
          }
        }
      }
    });

    // 4. Tasks due today or overdue
    tasks.forEach(task => {
      if (task.status !== 'Completed') {
        const dueDate = parseISO(task.dueDate);
        const startOfDue = startOfDay(dueDate);
        
        if (isBefore(startOfDue, today) || isSameDay(startOfDue, today)) {
          const isOverdue = isBefore(startOfDue, today);
          generated.push({
            id: `task_${task.id}_${dueDate.toISOString()}`,
            type: 'task_due',
            title: isOverdue ? 'Overdue Task' : 'Task Due Today',
            description: task.title,
            date: dueDate,
            recordName: task.title,
            recordId: task.id
          });
        }
      }
    });

    // 5. Pending booking requests
    pendingBookings.forEach(booking => {
      const itemsList = Array.isArray(booking.items)
        ? booking.items.map((i: any) => i.packageName || i.name).filter(Boolean).join(', ')
        : (booking.packageName || booking.type || 'Package Request');
      const priceText = typeof booking.totalPrice === 'number' ? ` (${booking.totalPrice} EGP)` : '';

      generated.push({
        id: `booking_req_${booking.id}`,
        type: 'booking_request',
        title: 'New Booking Request',
        description: `${booking.clientName || 'Client'} requested: ${itemsList}${priceText}`,
        date: booking.createdAt ? parseISO(booking.createdAt) : today,
        recordName: booking.clientName || 'Client',
        recordId: booking.id
      });
    });

    // Sort by date (newest first for tasks/events, but here we can just show tasks first, then birthdays, etc.)
    generated.sort((a, b) => b.date.getTime() - a.date.getTime());
    
    setNotifications([...systemNotifications, ...generated]);
  }, [clients, tasks, pendingBookings, systemNotifications]);

  const activeNotifications = useMemo(() => notifications.filter(n => {
    if (n.source === 'system') return !(n.readBy || []).includes(currentUser?.id || '');
    return !dismissedIds.has(n.id);
  }), [notifications, dismissedIds, currentUser?.id]);

  const getNotificationDestination = (notification: AppNotification) => {
    switch (notification.type) {
      case 'booking_request':
      case 'class_booking_created':
        return {
          tab: 'bookings',
          search: notification.recordName,
          clientId: notification.data?.clientId || notification.recordId,
        };
      case 'class_waitlist_joined':
        return {
          tab: 'class-manager',
          search: notification.data?.className || notification.recordName,
          clientId: notification.data?.clientId,
        };
      case 'task_due':
        return {
          tab: 'tasks',
          search: notification.recordName,
        };
      case 'lead_stale':
      case 'member_expiring':
      case 'birthday':
        return {
          tab: 'clients',
          search: notification.recordName,
          clientId: notification.recordId,
        };
      default:
        return {
          tab: 'dashboard',
          search: notification.recordName,
          clientId: notification.data?.clientId,
        };
    }
  };

  useEffect(() => {
    const tabCounts = activeNotifications.reduce<Record<string, number>>((counts, notification) => {
      const destination = getNotificationDestination(notification);
      counts[destination.tab] = (counts[destination.tab] || 0) + 1;
      return counts;
    }, {});

    window.dispatchEvent(new CustomEvent('crm:notification-tab-counts', { detail: tabCounts }));
  }, [activeNotifications]);

  const markNotificationRead = (notification: AppNotification) => {
    if (!currentUser?.id) return;

    if (notification.source === 'system') {
      updateDoc(doc(db, 'systemNotifications', notification.id), {
        readBy: arrayUnion(currentUser.id),
        updatedAt: new Date().toISOString()
      }).catch(err => {
        console.error("Failed to mark system notification read", err);
      });
      return;
    }

    setDismissedIds(prev => {
      const next = new Set(prev);
      next.add(notification.id);
      const arr = Array.from(next);
      localStorage.setItem(`crm_notifications_dismissed_${currentUser.id}`, JSON.stringify(arr));
      updateUser(currentUser.id, { dismissedNotifications: arr }).catch(err => {
        console.error("Failed to save dismissed notification to DB", err);
      });
      return next;
    });
  };

  const handleNotificationClick = (notification: AppNotification) => {
    const destination = getNotificationDestination(notification);
    setActiveTab(destination.tab);
    if (destination.search) {
      setSearchQuery(destination.search);
    }
    if (destination.tab === 'clients' && destination.clientId) {
      setActiveClientId(destination.clientId);
    }
    markNotificationRead(notification);
    setIsOpen(false);
  };

  const getIcon = (type: NotificationType) => {
    switch (type) {
      case 'birthday': return <Gift className="h-4 w-4 text-pink-500" />;
      case 'lead_stale': return <Clock className="h-4 w-4 text-amber-500" />;
      case 'member_expiring': return <AlertTriangle className="h-4 w-4 text-destructive" />;
      case 'task_due': return <CheckSquare className="h-4 w-4 text-blue-500" />;
      case 'booking_request': return <ShoppingCart className="h-4 w-4 text-emerald-500" />;
      case 'class_booking_created': return <Volume2 className="h-4 w-4 text-emerald-500" />;
      case 'class_waitlist_joined': return <ShoppingCart className="h-4 w-4 text-amber-500" />;
      default: return <Bell className="h-4 w-4" />;
    }
  };

  return (
    <div className="relative" ref={dropdownRef}>
      <Button 
        variant="ghost" 
        size="icon" 
        className="relative h-8 w-8 sm:h-10 sm:w-10 rounded-full"
        onClick={() => setIsOpen(!isOpen)}
        title="Notifications"
      >
        <Bell className="h-4 w-4 sm:h-5 sm:w-5" />
        {activeNotifications.length > 0 && (
          <span className="absolute top-1 right-1 flex h-3.5 w-3.5 items-center justify-center rounded-full bg-destructive text-[9px] font-bold text-destructive-foreground ring-1 ring-background">
            {activeNotifications.length > 99 ? '99+' : activeNotifications.length}
          </span>
        )}
      </Button>

      {isOpen && (
        <div className="fixed top-[70px] left-4 right-4 w-auto md:absolute md:top-full md:left-auto md:right-0 md:w-80 sm:md:w-96 md:mt-2 rounded-md border bg-card shadow-lg z-50 overflow-hidden animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95">
          <div className="flex items-center justify-between p-4 border-b bg-muted/30">
            <h3 className="font-semibold text-sm">Notifications</h3>
            {activeNotifications.length > 0 && (
              <Button variant="ghost" size="sm" className="h-auto p-0 text-xs text-muted-foreground hover:text-foreground" onClick={dismissAll}>
                Dismiss all <Check className="ml-1 h-3 w-3" />
              </Button>
            )}
          </div>
          
          <div className="max-h-[400px] overflow-y-auto no-scrollbar">
            {activeNotifications.length === 0 ? (
              <div className="p-8 text-center text-muted-foreground text-sm flex flex-col items-center">
                <Bell className="h-8 w-8 opacity-20 mb-2" />
                <p>You have no new notifications.</p>
              </div>
            ) : (
              <div className="divide-y divide-border">
                {activeNotifications.map(notification => (
                  <div 
                    key={notification.id} 
                    className="flex flex-col p-3 sm:p-4 hover:bg-muted/50 cursor-pointer transition-colors"
                    onClick={() => handleNotificationClick(notification)}
                  >
                    <div className="flex justify-between items-start">
                      <div className="flex items-start gap-3">
                        <div className="mt-0.5 rounded-full bg-background p-1.5 shadow-sm border">
                          {getIcon(notification.type)}
                        </div>
                        <div>
                          <p className="text-sm font-medium leading-none mb-1">{notification.title}</p>
                          <p className="text-xs text-muted-foreground line-clamp-2">{notification.description}</p>
                        </div>
                      </div>
                      <Button 
                        variant="ghost" 
                        size="icon" 
                        className="h-6 w-6 text-muted-foreground hover:text-destructive shrink-0 ml-2" 
                        onClick={(e) => dismissNotification(notification.id, e)}
                      >
                        <X className="h-3 w-3" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
